name: Deploy Webdoc

on:
  push:
    branches:
      - master
      - webdoc
    paths:
      - '.github/workflows/deploy-webdoc.yml'
      - 'web/**'

jobs:
  deploy:
    if: startsWith(github.repository, 'qd-today/qd')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.24.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/docs/.vitepress/dist